name: Build Binaries
on: [push, pull_request]

jobs:
  build-win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make mingw-w64-x86_64-toolchain mingw-w64-x86_64-libelf mingw-w64-x86_64-SDL2
      - name: Build Emulator
        run: |
          CROSS_COMPILE_WINDOWS=1 SDL2CONFIG=sdl2-config make V=1 -j2
          mkdir emu_binaries
          cp $(which SDL2.dll) emu_binaries/.
          cp sdcard.img.zip emu_binaries/.
          cp x16emu.exe emu_binaries/.
          file emu_binaries/*
      - name: Download latest ROM
        id: download
        run: |
          gh run download -R commanderx16/x16-rom -n "ROM Image" --dir latest_rom
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy ROM
        run: |
          cp latest_rom/rom.bin emu_binaries/.
          cp latest_rom/*.sym emu_binaries/.
      - uses: actions/upload-artifact@v3
        with:
          name: X16-Emu Windows 64-bit
          path: emu_binaries/*
  build-win32:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make mingw-w64-i686-toolchain mingw-w64-i686-libelf mingw-w64-i686-SDL2
          path-type: inherit
      - name: Add /mingw32/bin to path
        run: echo "/mingw32/bin" >> $GITHUB_PATH
      - name: Build Emulator
        run: |
          WIN_SDL2=/mingw32 TARGET_CPU=x86 CROSS_COMPILE_WINDOWS=1 make V=1 -j2
          mkdir emu_binaries
          cp $(which SDL2.dll) emu_binaries/.
          cp sdcard.img.zip emu_binaries/.
          cp x16emu.exe emu_binaries/.
          file emu_binaries/*
      - name: Download latest ROM
        id: download
        run: |
          gh run download -R commanderx16/x16-rom -n "ROM Image" --dir latest_rom
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy ROM
        run: |
          cp latest_rom/rom.bin emu_binaries/.
          cp latest_rom/*.sym emu_binaries/.
      - uses: actions/upload-artifact@v3
        with:
          name: X16-Emu Windows 32-bit
          path: emu_binaries/*
  build-lin64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential make libsdl2-dev
      - name: Build Emulator
        run: |
          make V=1 -j3
          mkdir emu_binaries
          cp sdcard.img.zip emu_binaries/.
          cp x16emu emu_binaries/.
          file emu_binaries/*
      - name: Download latest ROM
        id: download
        run: |
          gh run download -R commanderx16/x16-rom -n "ROM Image" --dir latest_rom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy ROM
        run: |
          cp latest_rom/rom.bin emu_binaries/.
          cp latest_rom/*.sym emu_binaries/.
      - uses: actions/upload-artifact@v3
        with:
          name: X16-Emu Linux 64-bit
          path: emu_binaries/*
  build-darwin-11-x64:
    # this is currently macos-11, Big Sur
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: | 
          brew install make sdl2 
      - name: Build Emulator
        run: |
          MAC_STATIC=1 LIBSDL_FILE=/usr/local/Cellar/sdl2/*/lib/libSDL2.a make V=1 -j3
          mkdir emu_binaries
          cp sdcard.img.zip emu_binaries/.
          cp x16emu emu_binaries/.
          file emu_binaries/*
      - name: Download latest ROM
        id: download
        run: |
          gh run download -R commanderx16/x16-rom -n "ROM Image" --dir latest_rom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy ROM
        run: |
          cp latest_rom/rom.bin emu_binaries/.
          cp latest_rom/*.sym emu_binaries/.
      - uses: actions/upload-artifact@v3
        with:
          name: X16-Emu MacOS 11 Big Sur Intel 64-bit
          path: emu_binaries/*
  build-darwin-12-x64:
    # this is currently macos-12, Monterey
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: | 
          brew install make sdl2 
      - name: Build Emulator
        run: |
          MAC_STATIC=1 LIBSDL_FILE=/usr/local/Cellar/sdl2/*/lib/libSDL2.a make V=1 -j3
          mkdir emu_binaries
          cp sdcard.img.zip emu_binaries/.
          cp x16emu emu_binaries/.
          file emu_binaries/*
      - name: Download latest ROM
        id: download
        run: |
          gh run download -R commanderx16/x16-rom -n "ROM Image" --dir latest_rom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy ROM
        run: |
          cp latest_rom/rom.bin emu_binaries/.
          cp latest_rom/*.sym emu_binaries/.
      - uses: actions/upload-artifact@v3
        with:
          name: X16-Emu MacOS 12 Monterey Intel 64-bit
          path: emu_binaries/*
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential make libsdl2-dev
      - uses: mymindstorm/setup-emsdk@v12
      - name: Download latest ROM
        id: download
        run: |
          gh run download -R commanderx16/x16-rom -n "ROM Image" --dir latest_rom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Emulator
        run: |
          cp latest_rom/rom.bin .
          make V=1 -j3 wasm
          mkdir emu_binaries
          cp x16emu.data x16emu.html x16emu.js x16emu.wasm emu_binaries/
          mkdir emu_binaries/webassembly
          cp webassembly/styles.css webassembly/main.js emu_binaries/webassembly/
          file emu_binaries/*
      - uses: actions/upload-artifact@v3
        with:
          name: X16-Emu Webassembly
          path: emu_binaries/*
