name: Build Binaries
on: [push, pull_request]

jobs:
  build-win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make mingw-w64-x86_64-toolchain mingw-w64-x86_64-libelf mingw-w64-x86_64-SDL2
      - name: Build Emulator
        run: |
          CROSS_COMPILE_WINDOWS=1 SDL2CONFIG=sdl2-config make V=1 -j2
          mkdir emu_binaries
          cp $(which SDL2.dll) emu_binaries/.
          cp sdcard.img.zip emu_binaries/.
          cp x16emu.exe emu_binaries/.
          file emu_binaries/*
      - name: Download latest ROM
        id: download
        run: |
          gh run download -R commanderx16/x16-rom -n "ROM Image" --dir latest_rom
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy ROM
        run: |
          cp latest_rom/rom.bin emu_binaries/.
          cp latest_rom/*.sym emu_binaries/.
      - uses: actions/upload-artifact@v3
        with:
          name: X16-Emu Windows 64-bit
          path: emu_binaries/*
  build-lin64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential make libsdl2-dev
      - name: Build Emulator
        run: |
          make V=1 -j3
          mkdir emu_binaries
          cp sdcard.img.zip emu_binaries/.
          cp x16emu emu_binaries/.
          file emu_binaries/*
      - name: Download latest ROM
        id: download
        run: |
          gh run download -R commanderx16/x16-rom -n "ROM Image" --dir latest_rom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy ROM
        run: |
          cp latest_rom/rom.bin emu_binaries/.
          cp latest_rom/*.sym emu_binaries/.
      - uses: actions/upload-artifact@v3
        with:
          name: X16-Emu Linux 64-bit
          path: emu_binaries/*
  build-darwin-x64:
    # this is currently macos-11, Big Sur
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: | 
          brew install make sdl2 
      - name: Build Emulator
        run: |
          MAC_STATIC=1 LIBSDL_FILE=/usr/local/Cellar/sdl2/*/lib/libSDL2.a make V=1 -j3
          mkdir emu_binaries
          cp sdcard.img.zip emu_binaries/.
          cp x16emu emu_binaries/.
          file emu_binaries/*
      - name: Download latest ROM
        id: download
        run: |
          gh run download -R commanderx16/x16-rom -n "ROM Image" --dir latest_rom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy ROM
        run: |
          cp latest_rom/rom.bin emu_binaries/.
          cp latest_rom/*.sym emu_binaries/.
      - uses: actions/upload-artifact@v3
        with:
          name: X16-Emu Mac Intel 64-bit
          path: emu_binaries/*
